sidekiq:
  build: .
  dockerfile: Dockerfile_sidekiq
  links:
    - redis
  volumes:
    - .:/usr/src/app
  environment:
    - APP_CONFIG_REDIS_HOST=redis

nginx:
  build: .
  dockerfile: Dockerfile_nginx
  links:
    - puma
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - .:/var/www/github-notifier/current
  environment:
    - APP_UPSTREAM_PUMA=puma

puma:
  build: .
  dockerfile: Dockerfile_puma
  links:
    - redis
  volumes:
    - .:/usr/src/app
  environment:
    - APP_CONFIG_REDIS_HOST=redis

redis:
  image: redis:3
  command: redis-server --appendonly yes
  volumes:
    - /data
