FROM debian:wheezy

RUN \
	apt-get update && \
	DEBIAN_FRONTEND=noninteractive \
		apt-get -y install autossh && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

RUN ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" && cat ~/.ssh/id_rsa.pub

EXPOSE 16379

CMD autossh -M 0 -L 16379:localhost:6379 redis-slave@web01.githubnotifier.io -N -p 91 -o "ServerAliveInterval 60" -o "ServerAliveCountMax 3" -o BatchMode=yes -o StrictHostKeyChecking=no
